#!/usr/bin/env python3
"""ref_dump.py — emit GOLDEN reference values from the authoritative Python
(core.py / sweep2.py) so the hedit JS port can be verified numerically.

Usage:  python3 ref_dump.py > golden.json

Everything here calls the REAL core.py functions — never a reimplementation.
The JS port in hedit.html must reproduce these within the tolerances stated in
sweep2/PORT_NOTES.md.
"""
import json, sys, os
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import core

HERE = os.path.dirname(os.path.abspath(__file__))


def arr(a, nd=6):
    return [[round(float(x), nd), round(float(y), nd)] for x, y in np.asarray(a)[:, :2]]


def poly_area(p):
    p = np.asarray(p)[:, :2]
    x, y = p[:, 0], p[:, 1]
    return float(0.5 * abs(np.dot(x, np.roll(y, 1)) - np.dot(y, np.roll(x, 1))))


def sample(a, n=24):
    """Evenly-spaced sample of a polyline/ring, so golden.json stays small."""
    a = np.asarray(a)
    idx = np.linspace(0, len(a) - 1, n).astype(int)
    return arr(a[idx])


out = {"_comment": "GOLDEN values from core.py — the JS port must match. Generated by ref_dump.py"}

# ---- 1. frame flatten ------------------------------------------------------
g, r, b = core.load_frame(os.path.join(HERE, "frame.svg"))
for name, P in (("green", g), ("red", r), ("blue", b)):
    seg = np.r_[0, np.cumsum(np.hypot(*np.diff(P, axis=0).T))]
    out[f"flatten_{name}"] = {
        "n": int(len(P)),
        "first": arr(P[:1])[0], "last": arr(P[-1:])[0],
        "arclen": round(float(seg[-1]), 4),
        "bbox": [round(float(P[:, 0].min()), 4), round(float(P[:, 1].min()), 4),
                 round(float(P[:, 0].max()), 4), round(float(P[:, 1].max()), 4)],
        "sample24": sample(P),
    }

# ---- 2. limaçon / _curve ---------------------------------------------------
out["curve_c2_b20"] = {"n": 720, "sample24": sample(core._curve(2.0, 20.0)),
                       "area": round(poly_area(core._curve(2.0, 20.0)), 6)}
out["curve_c1.4_b20"] = {"sample24": sample(core._curve(1.4, 20.0)),
                         "area": round(poly_area(core._curve(1.4, 20.0)), 6)}

# ---- 3. _resample ----------------------------------------------------------
out["resample_curve_c2_b20_to_90"] = {"sample24": sample(core._resample(core._curve(2.0, 20.0), 90))}

# ---- 4. limacon() (filleted outer) ----------------------------------------
for g_, b_ in ((0.30, 20.0), (0.10, 50.0), (0.49, 35.0)):
    e = core.limacon(g_, b_)
    out[f"limacon_g{g_}_b{b_}"] = {"n": int(len(e)), "area": round(poly_area(e), 6),
                                   "bbox": [round(float(e[:, 0].min()), 4), round(float(e[:, 1].min()), 4),
                                            round(float(e[:, 0].max()), 4), round(float(e[:, 1].max()), 4)],
                                   "sample24": sample(e)}

# ---- 5. section_rings ------------------------------------------------------
for g_, b_ in ((0.30, 20.0), (0.10, 50.0), (0.45, 40.0)):
    rings = core.section_rings(g_, b_)
    out[f"section_rings_g{g_}_b{b_}"] = {
        "nrings": len(rings),
        "rings": [{"n": int(len(R)), "area": round(poly_area(R), 6), "sample24": sample(R)} for R in rings],
    }

# ---- 6. _variable_bore (the acoustic wall schedule) ------------------------
for tau in (0.0, 0.5, 1.0):
    b_ = 45.0
    g_ = 0.30
    ext = core.limacon(g_, b_)
    iw = core._variable_bore(ext, 1.5 + 2.5 * tau, 2.5, 2.5 + 1.0 * tau)
    out[f"variable_bore_tau{tau}"] = {
        "t_spine": 1.5 + 2.5 * tau, "t_wing": 2.5, "t_shell": 2.5 + 1.0 * tau,
        "ext_area": round(poly_area(ext), 6),
        "bore_area": round(poly_area(iw), 6),
        "chamber_area": round(poly_area(ext) - poly_area(iw), 6),
        "n": int(len(iw)), "sample24": sample(iw),
    }


# ---- 7. structural section families + properties (appended) ---------------
def sec_props(rings):
    """Composite section properties. rings[0]=outer (force +area), rings[1:]=holes.
    Returns A, centroid, central second moments, principal moments."""
    M0 = M1x = M1y = M2xx = M2yy = M2xy = 0.0
    for k, R in enumerate(rings):
        P = np.asarray(R)[:, :2]
        x, y = P[:, 0], P[:, 1]
        x1, y1 = np.roll(x, -1), np.roll(y, -1)
        cross = x * y1 - x1 * y
        a = 0.5 * cross.sum()
        sign = 1.0 if k == 0 else -1.0        # holes subtract
        if (a > 0) != (sign > 0):
            x, y, x1, y1 = x[::-1], y[::-1], np.roll(x[::-1], -1), np.roll(y[::-1], -1)
            cross = x * y1 - x1 * y
            a = 0.5 * cross.sum()
        M0 += a
        M1x += (1/6.0) * ((x + x1) * cross).sum()
        M1y += (1/6.0) * ((y + y1) * cross).sum()
        M2xx += (1/12.0) * ((x*x + x*x1 + x1*x1) * cross).sum()      # about y-axis contribution -> Iyy
        M2yy += (1/12.0) * ((y*y + y*y1 + y1*y1) * cross).sum()      # -> Ixx
        M2xy += (1/24.0) * ((x*y1 + 2*x*y + 2*x1*y1 + x1*y) * cross).sum()
    A = M0
    cx, cy = M1x / A, M1y / A
    Iyy = M2xx - A * cx * cx          # about vertical axis through centroid
    Ixx = M2yy - A * cy * cy          # about horizontal axis through centroid
    Ixy = M2xy - A * cx * cy
    avg = 0.5 * (Ixx + Iyy)
    d = math.hypot(0.5 * (Ixx - Iyy), Ixy)
    Imax, Imin = avg + d, avg - d
    return dict(A=A, cx=cx, cy=cy, Ixx=Ixx, Iyy=Iyy, Ixy=Ixy, Imax=Imax, Imin=Imin)

import math
# U-beam neck: opened(g,b) exterior; bore = buffer(-crown) with crown=2gb
for g_, b_ in ((0.60, 40.0), (0.80, 45.0)):
    ext = core.opened(g_, b_)
    from shapely.geometry import Polygon as _Pg
    poly = _Pg(ext).buffer(0)
    crown = 2 * g_ * b_
    inn = poly.buffer(-crown, join_style="round")
    if getattr(inn, "geom_type", "") == "MultiPolygon":
        inn = max(inn.geoms, key=lambda gg: gg.area)
    rings = [np.array(poly.exterior.coords)]
    if not inn.is_empty and inn.area > 1e-6:
        rings.append(np.array(inn.exterior.coords))
    pr = sec_props(rings)
    out[f"opened_g{g_}_b{b_}"] = {"nrings": len(rings), "sample24": sample(ext),
        "props": {k: round(float(v), 4) for k, v in pr.items()}}

# Rose pillar: fl=(3+0.4 sin12θ)/3.4, outer r=h/2·fl; bore circle r=c/2
def rose_ext(h, M=90):
    th = np.linspace(0, 2*np.pi, M, endpoint=False)
    fl = (3 + 0.4*np.sin(12*th)) / 3.4
    return np.c_[(h/2)*fl*np.cos(th), h/2 + (h/2)*fl*np.sin(th)]
def rose_bore(h, c, M=90):
    th = np.linspace(0, 2*np.pi, M, endpoint=False)
    return np.c_[(c/2)*np.cos(th), h/2 + (c/2)*np.sin(th)]
for h_, c_ in ((120.0, 60.9),):
    ext = rose_ext(h_); bore = rose_bore(h_, c_)
    pr = sec_props([ext, bore])
    out[f"rose_h{h_}_c{c_}"] = {"sample24": sample(ext), "bore_area": round(poly_area(bore), 4),
        "props": {k: round(float(v), 4) for k, v in pr.items()}}

# soundbox structural: outer limaçon + variable bore, section props
for tau in (0.0, 1.0):
    b_ = 45.0
    ext = core.limacon(0.30, b_)
    iw = core._variable_bore(ext, 1.5+2.5*tau, 2.5, 2.5+1.0*tau)
    pr = sec_props([ext, iw])
    out[f"soundbox_props_tau{tau}"] = {"props": {k: round(float(v), 4) for k, v in pr.items()}}

# neck U-beam plate_u(PLATE_OUT, PLATE_LEG, H)
for ow_,lw_,H_ in ((35.3,3.4,120.0),(35.3,3.4,80.0)):
    ext=core.plate_u(ow_,lw_,H_)
    pr=sec_props([ext])
    out[f"plate_u_{ow_}_{lw_}_{H_}"]={"sample8":[[round(float(x),4),round(float(y),4)] for x,y in ext],"props":{k:round(float(v),4) for k,v in pr.items()}}

json.dump(out, sys.stdout, indent=1)
print()
